apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "nfs-client-provisioner.fullname" . }}
  labels:
    type: nfs
spec:
  storageClassName: {{ .Values.storageClassName | quote }}
  capacity:
    storage: {{ .Values.capacity | quote }}
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name | quote }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc-capacity | quote }}